version: '3.8'

services:
  web:
    build: ./mailsender
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mailsender:/usr/src/mailsender
    ports:
      - 8000:8000
    env_file:
      - ./mailsender/.env.dev
    depends_on:
      - db
      - redis
  redis:
    image: redis:alpine
    command: redis-server
    expose:
      - 6379
    restart: unless-stopped
  celery:
    build:
      context: ./mailsender/
      dockerfile: Dockerfile-celery
    command: celery -A mailtasks worker --loglevel=info --concurrency 1 -E
    env_file:
      - ./mailsender/.env.dev
    volumes:
      - ./mailsender:/usr/src/mailsender
    depends_on:
      - db
      - redis
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mailsender

volumes:
  postgres_data: