FROM python:2.7-alpine

# set work directory
WORKDIR /usr/src/mailsender

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN apk update && \
    apk add --virtual build-deps gcc python2-dev musl-dev && \
    apk add postgresql-dev

RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# copy project
COPY . .
